Repository Interacao-Humano-Computador/2023.1-Alistamento, pull requests merged in 2023-05, with the labels that each got.

#46 Atas e histórico de versão
  README.md
  docs/atas/ata1.md
  docs/atas/ata2.md
  docs/atas/ata3.md
  docs/atas/ata4.md
  docs/atas/template.md
  docs/img/home/site.png
  docs/index.md
  mkdocs.yml
Labels: bug, documentation, enhancement

#47 Ferramentas
  README.md
  docs/analise_requisitos/aspectos_eticos.md
  docs/atas/ata1.md
  docs/atas/ata2.md
  docs/atas/ata3.md
  docs/img/icones/chrome.svg
  docs/img/icones/docs.svg
  docs/img/icones/figma.svg
  docs/img/icones/firefox.svg
  docs/img/icones/forms.png
  docs/img/icones/github.png
  docs/img/icones/github.svg
  docs/img/icones/microsoft-teams.svg
  docs/img/icones/miro.png
  docs/img/icones/teams.png
  docs/img/icones/telegram.png
  docs/img/icones/telegram.svg
  docs/img/icones/thispersondoesnotexist.png
  docs/img/icones/visual-studio-code.svg
  docs/img/icones/vscode.png
  docs/img/icones/youtube.png
  docs/img/icones/youtube.svg
  docs/planejamento/ferramentas.md
  mkdocs.yml
Labels: bug, documentation, enhancement

#48 Criação inicial da análise de tarefas
  docs/analise_requisitos/analise_tarefas.md
  docs/img/requisitos/diagrama.png
  docs/img/requisitos/hta.png
  mkdocs.yml
Labels: documentation

#55 Refatoração de arquivos
  docs/analise_requisitos/analise_tarefas.md
  docs/analise_requisitos/personas.md
  docs/img/requisitos/persona1.jpg
  docs/img/requisitos/persona2.jpg
  mkdocs.yml
Labels: bug

#56 Refatorações - parte 2
  docs/analise_requisitos/analise_tarefas.md
  docs/planejamento/avaliacoes/alistamento.md
  docs/planejamento/avaliacoes/escola.md
  docs/planejamento/avaliacoes/shopee.md
  docs/planejamento/avaliacoes/striker.md
  docs/planejamento/ferramentas.md
  docs/planejamento/metodologia.md
  docs/planejamento/processo_design.md
  docs/planejamento/sites_avaliados.md
Labels: bug

#60 Página de apresentações
  docs/analise_requisitos/analise_tarefas.md
  docs/apresentacoes.md
  mkdocs.yml
Labels: documentation, enhancement

#67 Adição das metas de usabilidade
  docs/analise_requisitos/metas_usabalidade.md
Labels: documentation

#78 Atualização do Cronograma e Apresentação da Etapa 3
  docs/analise_requisitos/guia_estilo.md
  docs/apresentacoes.md
  docs/planejamento/cronograma.md
  docs/planejamento/cronograma_real.md
Labels: bug, documentation

#84 Adição do planejamento da avaliação dos storyboards
  docs/design_avaliacao_desenvolvimento/nivel1/storyboard/planejamento_avaliacao.md
Labels: documentation

#88 Storyboard gabriel
  docs/design_avaliacao_desenvolvimento/nivel1/storyboard/storyboard.md
  docs/img/requisitos/storyboard.jpg
Labels: documentation

#89 Update storyboard.md
  docs/design_avaliacao_desenvolvimento/nivel1/storyboard/storyboard.md
Labels: bug, documentation

#91 Atualização storyboard
  docs/design_avaliacao_desenvolvimento/nivel1/storyboard/storyboard.md
  mkdocs.yml
Labels: documentation

#95 Atualizações pontuais
  docs/design_avaliacao_desenvolvimento/nivel1/storyboard/planejamento_avaliacao.md
Labels: bug

#105 Img prototipo papel
  docs/img/design_avaliacao/acompanhar_alistamento.jpg
  docs/img/design_avaliacao/ja_me_alistei.jpg
  docs/img/design_avaliacao/locais_de_alistamento.jpg
  docs/img/design_avaliacao/locais_de_alistamento_2.jpg
  docs/img/design_avaliacao/menu_protótipo_de_papel.jpg
  docs/img/design_avaliacao/quero_me_alistar_1.jpg
  docs/img/design_avaliacao/quero_me_alistar_2.jpg
  docs/img/design_avaliacao/quero_me_alistar_3.jpg
  docs/img/design_avaliacao/quero_me_alistar_4.jpg
  docs/img/design_avaliacao/quero_me_alistar_5.jpg
  docs/img/design_avaliacao/requerer_certificado.jpg
Labels: documentation

#107 Update planejamento-relato-avaliacao-prototipo-papel.md
  docs/design_avaliacao_desenvolvimento/nivel2/planejamento-relato-avaliacao-prototipo-papel.md
Labels: documentation, important

#110 Atualização protótipo papel
  docs/design_avaliacao_desenvolvimento/nivel2/planejamento-relato-avaliacao-prototipo-papel.md
  docs/design_avaliacao_desenvolvimento/nivel2/protótipo_de_papel.md
Labels: documentation

#112 Resolvendo bugs
  docs/design_avaliacao_desenvolvimento/nivel2/prototipo_de_papel.md
  docs/img/design_avaliacao/menu_prototipo_de_papel.jpg
  mkdocs.yml
Labels: bug

#114 Adicionando arquivos da entrega 5
  docs/apresentacoes.md
  docs/design_avaliacao_desenvolvimento/nivel2/planejamento-avaliacao-prototipo-papel.md
  docs/planejamento/cronograma_real.md
Labels: documentation
